main: farmhunt.Game
name: FarmHunt
version: 1.0.1
description: FarmHunt
website: https://devras.info
author: kemq_
softdepend: [LibsDisguises, ViaVersion, ProtocolLib]

commands:
  farmhunt:
    aliases: [fh]
    description: Configuration Game Settings
    permission: farmhunt.admin
    permission-message: You don't have permission <permission>
    usage: /<command> | /<command> spawn


permissions:
  farmhunt.admin:
    default: op

